CREATE TABLE IF NOT EXISTS exams(
  id SERIAL PRIMARY KEY,
  name VARCHAR NOT NULL,
  type VARCHAR NOT NULL,
  status BOOLEAN DEFAULT true NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP,
  deleted_at TIMESTAMP
)

CREATE TABLE IF NOT EXISTS labs (
  id SERIAL PRIMARY KEY,
  name VARCHAR NOT NULL,
  address VARCHAR NOT NULL,
  status BOOLEAN DEFAULT true NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP,
  deleted_at TIMESTAMP
)

CREATE TABLE IF NOT EXISTS labs_exams (
  id SERIAL PRIMARY KEY,
  exam_id INTEGER NOT NULL,
  lab_id INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL,
  CONSTRAINT fk_exam FOREIGN KEY (exam_id) REFERENCES exams(id),
  CONSTRAINT fk_lab FOREIGN KEY (lab_id) REFERENCES labs(id) 
)

